//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArenaStars.GameLogsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ArenaStars.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BackgroundPicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BanDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BanReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.Game[] GamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTerminatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLoggedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User.RankEnum RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.Report[] ReportListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SignUpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SteamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.Tournament[] TournamentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BackgroundPic {
            get {
                return this.BackgroundPicField;
            }
            set {
                if ((object.ReferenceEquals(this.BackgroundPicField, value) != true)) {
                    this.BackgroundPicField = value;
                    this.RaisePropertyChanged("BackgroundPic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BanDuration {
            get {
                return this.BanDurationField;
            }
            set {
                if ((this.BanDurationField.Equals(value) != true)) {
                    this.BanDurationField = value;
                    this.RaisePropertyChanged("BanDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BanReason {
            get {
                return this.BanReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.BanReasonField, value) != true)) {
                    this.BanReasonField = value;
                    this.RaisePropertyChanged("BanReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Elo {
            get {
                return this.EloField;
            }
            set {
                if ((this.EloField.Equals(value) != true)) {
                    this.EloField = value;
                    this.RaisePropertyChanged("Elo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.Game[] Games {
            get {
                return this.GamesField;
            }
            set {
                if ((object.ReferenceEquals(this.GamesField, value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTerminated {
            get {
                return this.IsTerminatedField;
            }
            set {
                if ((this.IsTerminatedField.Equals(value) != true)) {
                    this.IsTerminatedField = value;
                    this.RaisePropertyChanged("IsTerminated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLoggedIn {
            get {
                return this.LastLoggedInField;
            }
            set {
                if ((this.LastLoggedInField.Equals(value) != true)) {
                    this.LastLoggedInField = value;
                    this.RaisePropertyChanged("LastLoggedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePic {
            get {
                return this.ProfilePicField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePicField, value) != true)) {
                    this.ProfilePicField = value;
                    this.RaisePropertyChanged("ProfilePic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User.RankEnum Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.Report[] ReportList {
            get {
                return this.ReportListField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportListField, value) != true)) {
                    this.ReportListField = value;
                    this.RaisePropertyChanged("ReportList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SignUpDate {
            get {
                return this.SignUpDateField;
            }
            set {
                if ((this.SignUpDateField.Equals(value) != true)) {
                    this.SignUpDateField = value;
                    this.RaisePropertyChanged("SignUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SteamId {
            get {
                return this.SteamIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SteamIdField, value) != true)) {
                    this.SteamIdField = value;
                    this.RaisePropertyChanged("SteamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.Tournament[] Tournaments {
            get {
                return this.TournamentsField;
            }
            set {
                if ((object.ReferenceEquals(this.TournamentsField, value) != true)) {
                    this.TournamentsField = value;
                    this.RaisePropertyChanged("Tournaments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="User.RankEnum", Namespace="http://schemas.datacontract.org/2004/07/ArenaStars.Models")]
        public enum RankEnum : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unranked = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Bronze = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Silver = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Gold = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Platinum = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Diamond = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Challanger = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Master = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Grandmaster = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Legend = 9,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/ArenaStars.Models")]
    [System.SerializableAttribute()]
    public partial class Game : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.GameStats[] GameStatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User[] ParticipantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.Game.GameTypeEnum TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User WinnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.GameStats[] GameStats {
            get {
                return this.GameStatsField;
            }
            set {
                if ((object.ReferenceEquals(this.GameStatsField, value) != true)) {
                    this.GameStatsField = value;
                    this.RaisePropertyChanged("GameStats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Map {
            get {
                return this.MapField;
            }
            set {
                if ((object.ReferenceEquals(this.MapField, value) != true)) {
                    this.MapField = value;
                    this.RaisePropertyChanged("Map");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User[] Participants {
            get {
                return this.ParticipantsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipantsField, value) != true)) {
                    this.ParticipantsField = value;
                    this.RaisePropertyChanged("Participants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.Game.GameTypeEnum Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerField, value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Game.GameTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/ArenaStars.Models")]
        public enum GameTypeEnum : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ranked = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unranked = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Tournament = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Challange = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/ArenaStars.Models")]
    [System.SerializableAttribute()]
    public partial class Report : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.Report.ReasonEnum ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User ReportedUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User ReporteeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SubmittedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.Report.ReasonEnum Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((this.ReasonField.Equals(value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User ReportedUser {
            get {
                return this.ReportedUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportedUserField, value) != true)) {
                    this.ReportedUserField = value;
                    this.RaisePropertyChanged("ReportedUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User Reportee {
            get {
                return this.ReporteeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporteeField, value) != true)) {
                    this.ReporteeField = value;
                    this.RaisePropertyChanged("Reportee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SubmittedDate {
            get {
                return this.SubmittedDateField;
            }
            set {
                if ((this.SubmittedDateField.Equals(value) != true)) {
                    this.SubmittedDateField = value;
                    this.RaisePropertyChanged("SubmittedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Report.ReasonEnum", Namespace="http://schemas.datacontract.org/2004/07/ArenaStars.Models")]
        public enum ReasonEnum : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Cheating = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Toxic = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Griefing = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Harassment = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Offensive_Content = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Other = 5,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tournament", Namespace="http://schemas.datacontract.org/2004/07/ArenaStars.Models")]
    [System.SerializableAttribute()]
    public partial class Tournament : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CheckInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.Game[] GamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasEndedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User[] InvitedPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User.RankEnum MaxRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User.RankEnum MinRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User[] ParticipantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrophyPicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.Tournament.TournamentTypeEnum TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.User WinnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CheckInDate {
            get {
                return this.CheckInDateField;
            }
            set {
                if ((this.CheckInDateField.Equals(value) != true)) {
                    this.CheckInDateField = value;
                    this.RaisePropertyChanged("CheckInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.Game[] Games {
            get {
                return this.GamesField;
            }
            set {
                if ((object.ReferenceEquals(this.GamesField, value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasEnded {
            get {
                return this.HasEndedField;
            }
            set {
                if ((this.HasEndedField.Equals(value) != true)) {
                    this.HasEndedField = value;
                    this.RaisePropertyChanged("HasEnded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User[] InvitedPlayers {
            get {
                return this.InvitedPlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.InvitedPlayersField, value) != true)) {
                    this.InvitedPlayersField = value;
                    this.RaisePropertyChanged("InvitedPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLive {
            get {
                return this.IsLiveField;
            }
            set {
                if ((this.IsLiveField.Equals(value) != true)) {
                    this.IsLiveField = value;
                    this.RaisePropertyChanged("IsLive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User.RankEnum MaxRank {
            get {
                return this.MaxRankField;
            }
            set {
                if ((this.MaxRankField.Equals(value) != true)) {
                    this.MaxRankField = value;
                    this.RaisePropertyChanged("MaxRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User.RankEnum MinRank {
            get {
                return this.MinRankField;
            }
            set {
                if ((this.MinRankField.Equals(value) != true)) {
                    this.MinRankField = value;
                    this.RaisePropertyChanged("MinRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User[] Participants {
            get {
                return this.ParticipantsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipantsField, value) != true)) {
                    this.ParticipantsField = value;
                    this.RaisePropertyChanged("Participants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerLimit {
            get {
                return this.PlayerLimitField;
            }
            set {
                if ((this.PlayerLimitField.Equals(value) != true)) {
                    this.PlayerLimitField = value;
                    this.RaisePropertyChanged("PlayerLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrophyPic {
            get {
                return this.TrophyPicField;
            }
            set {
                if ((object.ReferenceEquals(this.TrophyPicField, value) != true)) {
                    this.TrophyPicField = value;
                    this.RaisePropertyChanged("TrophyPic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.Tournament.TournamentTypeEnum Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.User Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerField, value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Tournament.TournamentTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/ArenaStars.Models")]
        public enum TournamentTypeEnum : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Veteran = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AllStars = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Open = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Invite = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unproven = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameStats", Namespace="http://schemas.datacontract.org/2004/07/ArenaStars.Models")]
    [System.SerializableAttribute()]
    public partial class GameStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeathsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArenaStars.GameLogsServiceReference.Game GameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HsRatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SteamIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Deaths {
            get {
                return this.DeathsField;
            }
            set {
                if ((this.DeathsField.Equals(value) != true)) {
                    this.DeathsField = value;
                    this.RaisePropertyChanged("Deaths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArenaStars.GameLogsServiceReference.Game Game {
            get {
                return this.GameField;
            }
            set {
                if ((object.ReferenceEquals(this.GameField, value) != true)) {
                    this.GameField = value;
                    this.RaisePropertyChanged("Game");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HsRatio {
            get {
                return this.HsRatioField;
            }
            set {
                if ((this.HsRatioField.Equals(value) != true)) {
                    this.HsRatioField = value;
                    this.RaisePropertyChanged("HsRatio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kills {
            get {
                return this.KillsField;
            }
            set {
                if ((this.KillsField.Equals(value) != true)) {
                    this.KillsField = value;
                    this.RaisePropertyChanged("Kills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SteamId {
            get {
                return this.SteamIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SteamIdField, value) != true)) {
                    this.SteamIdField = value;
                    this.RaisePropertyChanged("SteamId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameLogsServiceReference.IGameService")]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/ReadServerLogs", ReplyAction="http://tempuri.org/IGameService/ReadServerLogsResponse")]
        void ReadServerLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/ReadServerLogs", ReplyAction="http://tempuri.org/IGameService/ReadServerLogsResponse")]
        System.Threading.Tasks.Task ReadServerLogsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/StartGame", ReplyAction="http://tempuri.org/IGameService/StartGameResponse")]
        void StartGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/StartGame", ReplyAction="http://tempuri.org/IGameService/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/DeleteLog", ReplyAction="http://tempuri.org/IGameService/DeleteLogResponse")]
        void DeleteLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/DeleteLog", ReplyAction="http://tempuri.org/IGameService/DeleteLogResponse")]
        System.Threading.Tasks.Task DeleteLogAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/SaveStatsAndGame", ReplyAction="http://tempuri.org/IGameService/SaveStatsAndGameResponse")]
        void SaveStatsAndGame(ArenaStars.GameLogsServiceReference.User playerA, ArenaStars.GameLogsServiceReference.User playerB, ArenaStars.GameLogsServiceReference.Game gameType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/SaveStatsAndGame", ReplyAction="http://tempuri.org/IGameService/SaveStatsAndGameResponse")]
        System.Threading.Tasks.Task SaveStatsAndGameAsync(ArenaStars.GameLogsServiceReference.User playerA, ArenaStars.GameLogsServiceReference.User playerB, ArenaStars.GameLogsServiceReference.Game gameType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/WhitelistPlayers", ReplyAction="http://tempuri.org/IGameService/WhitelistPlayersResponse")]
        void WhitelistPlayers(ArenaStars.GameLogsServiceReference.User _playerA, ArenaStars.GameLogsServiceReference.User _playerB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/WhitelistPlayers", ReplyAction="http://tempuri.org/IGameService/WhitelistPlayersResponse")]
        System.Threading.Tasks.Task WhitelistPlayersAsync(ArenaStars.GameLogsServiceReference.User _playerA, ArenaStars.GameLogsServiceReference.User _playerB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : ArenaStars.GameLogsServiceReference.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.ClientBase<ArenaStars.GameLogsServiceReference.IGameService>, ArenaStars.GameLogsServiceReference.IGameService {
        
        public GameServiceClient() {
        }
        
        public GameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ReadServerLogs() {
            base.Channel.ReadServerLogs();
        }
        
        public System.Threading.Tasks.Task ReadServerLogsAsync() {
            return base.Channel.ReadServerLogsAsync();
        }
        
        public void StartGame() {
            base.Channel.StartGame();
        }
        
        public System.Threading.Tasks.Task StartGameAsync() {
            return base.Channel.StartGameAsync();
        }
        
        public void DeleteLog() {
            base.Channel.DeleteLog();
        }
        
        public System.Threading.Tasks.Task DeleteLogAsync() {
            return base.Channel.DeleteLogAsync();
        }
        
        public void SaveStatsAndGame(ArenaStars.GameLogsServiceReference.User playerA, ArenaStars.GameLogsServiceReference.User playerB, ArenaStars.GameLogsServiceReference.Game gameType) {
            base.Channel.SaveStatsAndGame(playerA, playerB, gameType);
        }
        
        public System.Threading.Tasks.Task SaveStatsAndGameAsync(ArenaStars.GameLogsServiceReference.User playerA, ArenaStars.GameLogsServiceReference.User playerB, ArenaStars.GameLogsServiceReference.Game gameType) {
            return base.Channel.SaveStatsAndGameAsync(playerA, playerB, gameType);
        }
        
        public void WhitelistPlayers(ArenaStars.GameLogsServiceReference.User _playerA, ArenaStars.GameLogsServiceReference.User _playerB) {
            base.Channel.WhitelistPlayers(_playerA, _playerB);
        }
        
        public System.Threading.Tasks.Task WhitelistPlayersAsync(ArenaStars.GameLogsServiceReference.User _playerA, ArenaStars.GameLogsServiceReference.User _playerB) {
            return base.Channel.WhitelistPlayersAsync(_playerA, _playerB);
        }
    }
}
